"""Add superset_group_id to workout_exercises

Revision ID: 9991b8323957
Revises: da26ee9e5945
Create Date: 2026-01-23 22:37:39.239409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9991b8323957'
down_revision = 'da26ee9e5945'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercises', sa.Column('superset_group_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_workout_exercises_superset_group_id'), 'workout_exercises', ['superset_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_exercises_superset_group_id'), table_name='workout_exercises')
    op.drop_column('workout_exercises', 'superset_group_id')
    # ### end Alembic commands ###
