"""add_is_rare_gate_to_user_dungeons

Revision ID: da26ee9e5945
Revises: e741d5fb553c
Create Date: 2026-01-23 21:38:02.031270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da26ee9e5945'
down_revision = 'e741d5fb553c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_dungeons', sa.Column('is_rare_gate', sa.Boolean(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_dungeons', 'is_rare_gate')
    # ### end Alembic commands ###
