"""Add friend_requests and friendships tables

Revision ID: e741d5fb553c
Revises: add_username_to_users
Create Date: 2026-01-18 00:31:10.913364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e741d5fb553c'
down_revision = 'add_username_to_users'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('receiver_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='friendrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id', 'receiver_id', name='uq_friend_request_sender_receiver')
    )
    op.create_index('ix_friend_request_receiver_status', 'friend_requests', ['receiver_id', 'status'], unique=False)
    op.create_index('ix_friend_request_sender_status', 'friend_requests', ['sender_id', 'status'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('friend_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='uq_friendship_user_friend')
    )
    op.create_index('ix_friendship_friend_id', 'friendships', ['friend_id'], unique=False)
    op.create_index('ix_friendship_user_id', 'friendships', ['user_id'], unique=False)
    op.create_foreign_key(None, 'prs', 'sets', ['set_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prs', type_='foreignkey')
    op.drop_index('ix_friendship_user_id', table_name='friendships')
    op.drop_index('ix_friendship_friend_id', table_name='friendships')
    op.drop_table('friendships')
    op.drop_index('ix_friend_request_sender_status', table_name='friend_requests')
    op.drop_index('ix_friend_request_receiver_status', table_name='friend_requests')
    op.drop_table('friend_requests')
    # ### end Alembic commands ###
