name: FitnessApp
options:
  bundleIdPrefix: com.fitnessapp
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: D69T4MH7XQ
    CODE_SIGN_STYLE: Automatic
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UIRequiresFullScreen: YES
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    ENABLE_PREVIEWS: YES

targets:
  FitnessApp:
    type: application
    platform: iOS
    sources:
      - path: FitnessApp
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nickchua.fitnessapp
        PRODUCT_NAME: FitnessApp
        INFOPLIST_KEY_CFBundleDisplayName: "Fitness Tracker"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    entitlements:
      path: FitnessApp/FitnessApp.entitlements
      properties:
        com.apple.developer.healthkit: true
    capabilities:
      HealthKit: true
    info:
      path: FitnessApp/Info.plist
      properties:
        CFBundleName: FitnessApp
        CFBundleDisplayName: Fitness Tracker
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        NSHealthShareUsageDescription: "Arise syncs your steps, calories, and activity data to track your overall fitness progress alongside your workouts."
        NSHealthUpdateUsageDescription: "Arise can log your strength workouts to Apple Health."
        UIBackgroundModes:
          - fetch
          - processing

  FitnessAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: FitnessAppTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: FitnessApp
    settings:
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/FitnessApp.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/FitnessApp"
      BUNDLE_LOADER: "$(TEST_HOST)"

schemes:
  FitnessApp:
    build:
      targets:
        FitnessApp: all
        FitnessAppTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - FitnessAppTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
