"""initial schema

Revision ID: 7bdc998df9e6
Revises:
Create Date: 2026-08-15 23:25:16.006467

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7bdc998df9e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('regions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('tour_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_days',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('drive_times',
    sa.Column('region_a', sa.String(), nullable=False),
    sa.Column('region_b', sa.String(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('flags', sa.String(), nullable=False),
    sa.CheckConstraint('region_a <= region_b', name='ck_drive_pair_ordered'),
    sa.ForeignKeyConstraint(['region_a'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['region_b'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('region_a', 'region_b')
    )
    op.create_table('ideas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('yelp_url', sa.String(), nullable=True),
    sa.Column('maps_url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recommended_by', sa.String(), nullable=True),
    sa.Column('reservation_rule', sa.Text(), nullable=True),
    sa.Column('closed_days', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('best_time', sa.String(), nullable=True),
    sa.Column('meal_tags', sa.String(), nullable=False),
    sa.Column('created_by_member_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("kind IN ('activity', 'restaurant')", name='ck_idea_kind'),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trip_day_id', sa.String(), nullable=False),
    sa.Column('idea_id', sa.String(), nullable=True),
    sa.Column('free_text_title', sa.String(), nullable=True),
    sa.Column('free_text_region_id', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('duration_override_min', sa.Integer(), nullable=True),
    sa.Column('fixed_start_time', sa.Time(), nullable=True),
    sa.Column('drive_override_min', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(idea_id IS NULL) != (free_text_title IS NULL)', name='ck_item_idea_xor_free_text'),
    sa.ForeignKeyConstraint(['free_text_region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_day_id'], ['trip_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('idea_id', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("value IN ('interested', 'must_go')", name='ck_vote_value'),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idea_id', 'member_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('schedule_items')
    op.drop_table('ideas')
    op.drop_table('drive_times')
    op.drop_table('trip_days')
    op.drop_table('regions')
    op.drop_table('members')
    op.drop_table('app_state')
    # ### end Alembic commands ###
