"""Add deleted_at to workout_sessions

Revision ID: 949a78c76812
Revises: 41fc1e5fb394
Create Date: 2025-12-30 19:08:52.258668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949a78c76812'
down_revision = '41fc1e5fb394'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_sessions', 'deleted_at')
    # ### end Alembic commands ###
