"""initial schema

Revision ID: aeba3e0dd4b6
Revises:
Create Date: 2026-03-22 01:17:16.501594

"""
# ruff: noqa: E501
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aeba3e0dd4b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('auth_provider', sa.Enum('email', 'apple', name='authprovider', create_constraint=True), nullable=False),
    sa.Column('apple_user_id', sa.String(length=255), nullable=True),
    sa.Column('default_buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('default_travel_mode', sa.Enum('driving', 'transit', 'walking', 'cycling', name='travelmode', create_constraint=True), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_apple_user_id'), 'users', ['apple_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('device_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_table('saved_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_saved_locations_user_name')
    )
    op.create_index(op.f('ix_saved_locations_user_id'), 'saved_locations', ['user_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('origin_location_id', sa.UUID(), nullable=True),
    sa.Column('origin_address', sa.String(length=500), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lng', sa.Float(), nullable=False),
    sa.Column('origin_is_current_location', sa.Boolean(), nullable=False),
    sa.Column('dest_location_id', sa.UUID(), nullable=True),
    sa.Column('dest_address', sa.String(length=500), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lng', sa.Float(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('travel_mode', sa.Enum('driving', 'transit', 'walking', 'cycling', name='travelmode', create_constraint=True), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'monitoring', 'notified', 'departed', 'completed', 'cancelled', name='tripstatus', create_constraint=True), nullable=False),
    sa.Column('monitoring_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_eta_seconds', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notify_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('notification_count', sa.Integer(), nullable=False),
    sa.Column('baseline_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calendar_event_id', sa.String(length=500), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dest_location_id'], ['saved_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['origin_location_id'], ['saved_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_arrival_time'), 'trips', ['arrival_time'], unique=False)
    op.create_index(op.f('ix_trips_calendar_event_id'), 'trips', ['calendar_event_id'], unique=False)
    op.create_index(op.f('ix_trips_notify_at'), 'trips', ['notify_at'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_index('ix_trips_user_status_arrival', 'trips', ['user_id', 'status', 'arrival_time'], unique=False)
    op.create_table('notifications_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.Enum('heads_up', 'prepare', 'leave_soon', 'leave_now', 'running_late', name='notificationtype', create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('eta_at_send_seconds', sa.Integer(), nullable=True),
    sa.Column('recommended_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_status', sa.Enum('pending', 'delivered', 'failed', 'dismissed', 'tapped', name='deliverystatus', create_constraint=True), nullable=False),
    sa.Column('fcm_message_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_log_sent_at'), 'notifications_log', ['sent_at'], unique=False)
    op.create_index(op.f('ix_notifications_log_trip_id'), 'notifications_log', ['trip_id'], unique=False)
    op.create_index(op.f('ix_notifications_log_user_id'), 'notifications_log', ['user_id'], unique=False)
    op.create_table('trip_eta_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('duration_in_traffic_seconds', sa.Integer(), nullable=False),
    sa.Column('traffic_model', sa.String(length=50), nullable=False),
    sa.Column('congestion_level', sa.Enum('unknown', 'light', 'moderate', 'heavy', 'severe', name='congestionlevel', create_constraint=True), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_eta_snapshots_checked_at'), 'trip_eta_snapshots', ['checked_at'], unique=False)
    op.create_index('ix_trip_eta_snapshots_trip_checked', 'trip_eta_snapshots', ['trip_id', 'checked_at'], unique=False)
    op.create_index(op.f('ix_trip_eta_snapshots_trip_id'), 'trip_eta_snapshots', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_eta_snapshots_trip_id'), table_name='trip_eta_snapshots')
    op.drop_index('ix_trip_eta_snapshots_trip_checked', table_name='trip_eta_snapshots')
    op.drop_index(op.f('ix_trip_eta_snapshots_checked_at'), table_name='trip_eta_snapshots')
    op.drop_table('trip_eta_snapshots')
    op.drop_index(op.f('ix_notifications_log_user_id'), table_name='notifications_log')
    op.drop_index(op.f('ix_notifications_log_trip_id'), table_name='notifications_log')
    op.drop_index(op.f('ix_notifications_log_sent_at'), table_name='notifications_log')
    op.drop_table('notifications_log')
    op.drop_index('ix_trips_user_status_arrival', table_name='trips')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_notify_at'), table_name='trips')
    op.drop_index(op.f('ix_trips_calendar_event_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_arrival_time'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_saved_locations_user_id'), table_name='saved_locations')
    op.drop_table('saved_locations')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_apple_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
